replace normal equations by QR decomposition
git-svn-id: svn://svn.code.sf.net/p/octave/code/trunk/octave-forge@4853 fc592f45-0881-4044-91ff-c96495a54512

diff --git a/main/octgpr/src/configure b/main/octgpr/src/configure
--- a/main/octgpr/src/configure
+++ b/main/octgpr/src/configure
@@ -5229,15 +5229,15 @@ if test "$ac_res" != no; then
 
 fi
 
-{ echo "$as_me:$LINENO: checking for library containing dpotrs" >&5
-echo $ECHO_N "checking for library containing dpotrs... $ECHO_C" >&6; }
-if test "${ac_cv_search_dpotrs+set}" = set; then
+{ echo "$as_me:$LINENO: checking for library containing dgeqr2" >&5
+echo $ECHO_N "checking for library containing dgeqr2... $ECHO_C" >&6; }
+if test "${ac_cv_search_dgeqr2+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_func_search_save_LIBS=$LIBS
 cat >conftest.$ac_ext <<_ACEOF
       program main
-      call dpotrs
+      call dgeqr2
       end
 _ACEOF
 for ac_lib in '' goto atlas lapack; do
@@ -5265,7 +5265,7 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_search_dpotrs=$ac_res
+  ac_cv_search_dgeqr2=$ac_res
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -5275,21 +5275,153 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext
-  if test "${ac_cv_search_dpotrs+set}" = set; then
+  if test "${ac_cv_search_dgeqr2+set}" = set; then
   break
 fi
 done
-if test "${ac_cv_search_dpotrs+set}" = set; then
+if test "${ac_cv_search_dgeqr2+set}" = set; then
   :
 else
-  ac_cv_search_dpotrs=no
+  ac_cv_search_dgeqr2=no
 fi
 rm conftest.$ac_ext
 LIBS=$ac_func_search_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_search_dpotrs" >&5
-echo "${ECHO_T}$ac_cv_search_dpotrs" >&6; }
-ac_res=$ac_cv_search_dpotrs
+{ echo "$as_me:$LINENO: result: $ac_cv_search_dgeqr2" >&5
+echo "${ECHO_T}$ac_cv_search_dgeqr2" >&6; }
+ac_res=$ac_cv_search_dgeqr2
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+fi
+
+{ echo "$as_me:$LINENO: checking for library containing dorm2r" >&5
+echo $ECHO_N "checking for library containing dorm2r... $ECHO_C" >&6; }
+if test "${ac_cv_search_dorm2r+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dorm2r
+      end
+_ACEOF
+for ac_lib in '' goto atlas lapack; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_f77_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_dorm2r=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_dorm2r+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_dorm2r+set}" = set; then
+  :
+else
+  ac_cv_search_dorm2r=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_dorm2r" >&5
+echo "${ECHO_T}$ac_cv_search_dorm2r" >&6; }
+ac_res=$ac_cv_search_dorm2r
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+fi
+
+{ echo "$as_me:$LINENO: checking for library containing dtrtrs" >&5
+echo $ECHO_N "checking for library containing dtrtrs... $ECHO_C" >&6; }
+if test "${ac_cv_search_dtrtrs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dtrtrs
+      end
+_ACEOF
+for ac_lib in '' goto atlas lapack; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_f77_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_dtrtrs=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_dtrtrs+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_dtrtrs+set}" = set; then
+  :
+else
+  ac_cv_search_dtrtrs=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_dtrtrs" >&5
+echo "${ECHO_T}$ac_cv_search_dtrtrs" >&6; }
+ac_res=$ac_cv_search_dtrtrs
 if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
 
